[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
# runner = "gdb-multiarch -q -x openocd.gdb" # run in root of project

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip STM32F407VGTx"
rustflags = [
    # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
    # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
    "-C",
    # "link-arg=--nmagic",
    # LLD (shipped with the Rust toolchain) is used as the default linker
    "link-arg=-Tlink.x",
]
