[build]
target = ["thumbv7em-none-eabihf"]
# target = ["thumbv7em-none-eabihf", "x86_64-unknown-linux-gnu"]

# probe-run
#[target.thumbv7em-none-eabihf]
# runner = "probe-rs run --chip STM32F407VGTx"

# default runner starts a GDB sesssion, which requires OpenOCD to be running, e.g. :
## openocd -f interface/stlink.cfg -f target/stm32f4x.cfg
# modify link to openocd.gdb base on where to execute cargo run
[target.thumbv7em-none-eabihf]
# runner = "arm-none-eabi-gdb -q -x ../openocd.gdb"
runner = "gdb-multiarch -q -x openocd.gdb"
# runner = "gdb -q -x ../openocd.gdb"
rustflags = ["-C", "link-arg=-Tlink.x"]
